
CREATE TABLE IF NOT EXISTS `pintuan_products` (
  `Products_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Users_ID` varchar(10) NOT NULL,
  `Products_Name` varchar(50) NOT NULL,
  `Products_Category` varchar(255) NOT NULL DEFAULT '',
  `Products_Type` smallint(6) DEFAULT '0' COMMENT '产品类型',
  `Products_Parameter` varchar(255) DEFAULT NULL,
  `Products_PriceT` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '团购价格，现价',
  `Products_PriceD` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '单购价格，现价',
  `Products_PriceSd` decimal(11,2) DEFAULT '0.00' COMMENT '产品单购供货价',
  `Products_PriceSt` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '产品团购供货价',
  `Products_Profit` int(10) NOT NULL DEFAULT '0' COMMENT '产品利润百分比',
  `Products_Distributes` varchar(255) DEFAULT NULL COMMENT '详细介绍',
  `Products_JSON` text,
  `Products_BriefDescription` varchar(255) DEFAULT NULL COMMENT '简短介绍',
  `Products_IsShippingFree` tinyint(1) DEFAULT '0',
  `Products_Description` longtext,
  `Products_CreateTime` int(10) DEFAULT NULL,
  `Products_Count` int(10) DEFAULT '0' COMMENT '商品库存',
  `Products_Weight` decimal(10,2) DEFAULT '0.00',
  `Products_Sales` int(10) DEFAULT '0',
  `Products_Qrcode` varchar(200) DEFAULT NULL,
  `Products_IsVirtual` tinyint(1) DEFAULT '0',
  `Products_IsRecieve` tinyint(1) DEFAULT '0',
  `Products_Shipping` smallint(6) DEFAULT NULL COMMENT '模板id',
  `Shipping_Free_Company` smallint(6) DEFAULT '0' COMMENT '免运费时所指定的快递公司，0为所有快递公司均可',
  `Products_Business` varchar(10) DEFAULT NULL,
  `commission_ratio` int(5) DEFAULT '100' COMMENT '佣金所占利润的百分比',
  `Products_Index` int(10) DEFAULT '99999',
  `Products_Status` tinyint(1) DEFAULT '0',
  `nobi_ratio` int(10) DEFAULT '0',
  `platForm_Income_Reward` int(10) unsigned DEFAULT '0' COMMENT '平台发放比例',
  `area_Proxy_Reward` int(10) unsigned DEFAULT '0' COMMENT '区域代理占网站发放佣金比例',
  `sha_Reward` int(10) unsigned DEFAULT '0' COMMENT '股东分红比例',
  `click_count` int(11) DEFAULT '0' COMMENT '点击次数',
  `is_buy` int(1) DEFAULT '0' COMMENT '是否支持单独购买',
  `people_num` int(10) DEFAULT NULL COMMENT '拼团人数',
  `starttime` int(11) NOT NULL COMMENT '活动开始时',
  `stoptime` int(11) NOT NULL COMMENT '活动结束时间',
  `people_once` int(5) DEFAULT NULL COMMENT '每人每次限购个数',
  `order_process` tinyint(1) NOT NULL COMMENT '订单流程',
  `Is_Draw` tinyint(1) DEFAULT NULL COMMENT '抽奖',
  `Award_rule` varchar(255) NOT NULL COMMENT '抽奖规则',
  `shopproudent_id` int(20) DEFAULT NULL,
  `products_IsHot` tinyint(1) DEFAULT NULL COMMENT '热销',
  `products_IsNew` tinyint(1) DEFAULT NULL COMMENT '进口',
  `products_IsRecommend` tinyint(1) DEFAULT NULL COMMENT '促销',
  `pintuan_id` int(1) DEFAULT NULL,
  `products_SoldOut` tinyint(4) DEFAULT NULL,
  `Products_Credit` tinyint(1) DEFAULT NULL COMMENT '商家信誉',
  `Products_pinkage` tinyint(1) DEFAULT NULL COMMENT '包邮',
  `Products_refund` tinyint(1) DEFAULT NULL COMMENT '七天退款',
  `Products_compensation` tinyint(1) DEFAULT NULL COMMENT '假一赔十',
  `pintuan_type` tinyint(1) DEFAULT NULL COMMENT '拼团状态   0开启   1关闭',
  `Ratio` tinyint(1) DEFAULT NULL,
  `Team_Count` int(4) unsigned DEFAULT NULL COMMENT '总团数',
  `Products_FinanceRate` decimal(11,2) DEFAULT '0.00' COMMENT '网站提成百分比',
  `Biz_ID` int(10) DEFAULT NULL,
  `Products_FinanceType` tinyint(1) DEFAULT '0' COMMENT '0 按交易额比例 1 按供货价',
  PRIMARY KEY (`Products_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='拼团商品表，用于存储用户添加的商品记录';
